name: Java CI with Gradle

on:
  pull_request:
    branches: [ "yoon-test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: make main properties
      run: |
        cd ./src/main
        mkdir resource
        cd ./resource
        touch ./application.properties
        echo "${{ secrets.PROPERTIES_PROD }}" ./application.properties
      shell: bash
    
    - name: make test properties
      run: |
        cd ./src/test/
        mkdir resources
        cd ./resources
        touch ./application.properties
        echo "${{ secrets.TEST_PROPERTIES }}" > ./application.properties
      shell: bash
    - name: make test fcm json
      run: |
        cd ./src/test/resources
        mkdir firebase
        cd ./firebase
        touch ./monglemongle-firebase-adminsdk-zrey9-3a66b2259a.json
        echo "${{ secrets.FIREBASE_JSON }}" > ./monglemongle-firebase-adminsdk-zrey9-3a66b2259a.json
      shell: bash
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
